Instruments:
  BeamFlags:
    name: BeamFlags
    port: COM21
    dummy: False
    baudrate: 9600
    read_timeout: 0.1
    start_up_delay: 0.5      # Increase this if you have difficulty connecting
    instrument: hyperion.instrument.misc.beam_flags_instr/BeamFlagsInstr
    controller: hyperion.controller.generic.generic_serial_contr/GenericSerialController
    view: hyperion.view.misc.beam_flags_gui/BeamFlagsGui
    flag_states:
      red:   'r'                # character for arduino red state
      green: 'g'                # character for arduino green state
    gui_red_color:   rgb(255, 100, 100)
    gui_green_color: rgb(100, 255, 100)
    gui_state_update_ms: 100    # recommend 100,  update time in ms for the state indicators
    gui_flags:
      '1':                      # key-name should be the id-character for the arduino controller
        name: FilterA
        red_name: In
        green_name: Out
        shortkey: Ctrl+1
      '2':
        name: FilterB
        red_name: In
        green_name: Out
        shortkey: Ctrl+2
      '3':
        name: FilterC
        red_name: In
        green_name: Out
        shortkey: Ctrl+3