shutter_controls:
  - Closed
  - Opened
horz_width_multiple: 4
display:
  rotate: False
  reverse: True
  flip: True
data_file:
  confirm_overwrite: False
  autosave: 'Auto'  #Auto
  increment: False
timing:
  mode: 'Free Run'
  fast_safe: 'Fast'
  delay_time_s: 0
ascii_file: False



